# Generated by Django 5.2.1 on 2025-06-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codiAlumne", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                (
                    "curs",
                    models.CharField(
                        choices=[
                            ("1ESO", "1r ESO"),
                            ("2ESO", "2n ESO"),
                            ("3ESO", "3r ESO"),
                            ("4ESO", "4t ESO"),
                            ("1BAT", "1r Batxillerat"),
                            ("2BAT", "2n Batxillerat"),
                        ],
                        max_length=5,
                    ),
                ),
                ("correuElectronicAlumne", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titol", models.CharField(max_length=200)),
                ("text", models.TextField()),
                (
                    "autor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conte",
                        to="concursliterari.alumne",
                    ),
                ),
            ],
        ),
    ]
