# Generated by Django 5.2.1 on 2025-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concursliterari", "0002_alter_alumne_correuelectronicalumne"),
    ]

    operations = [
        migrations.AddField(
            model_name="conte",
            name="portada",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
