# Generated by Django 5.2.1 on 2025-06-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concursliterari", "0003_conte_portada"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_votant", models.GenericIPAddressField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "conte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vots",
                        to="concursliterari.conte",
                    ),
                ),
            ],
            options={
                "unique_together": {("conte", "ip_votant")},
            },
        ),
    ]
