# Generated by Django 5.2.1 on 2025-06-15 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concursliterari", "0004_vot"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vot",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="vot",
            name="ip_votant",
        ),
    ]
